name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      # - main # Enable if you want it to run for every commit to the main branch
      - v4
    paths:
      - 'quartz/**'
    

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Debug list files
        run: ls -al
        working-directory: ./quartz
      - name: Install Dependencies
        run: npm ci
        working-directory: ./quartz
      - name: Build Quartz
        run: npx quartz build
        working-directory: ./quartz
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: quartz/public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
